import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react'

function SimpleCounter() {
  const [count, setCount] = useState<number>(0)
  return (
    <div>
      <h1>I was clicked {count % 2 == 0 ? "even" : "odd"} number of times!</h1>
      <button onClick={() => setCount(count + 1)}>Click me!</button>
    </div>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <SimpleCounter />
      </main>
    </>
  )
}
